/* Autogenerated by png2wx.pl on Sun Apr  7 01:29:19 2013 */
#ifndef BITMAPS_H
#define BITMAPS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_bitmaps(void);

extern wxBitmap *_img_exp_sq;
extern wxBitmap *_img_oil_rig;
extern wxBitmap *_img_sector;
extern wxBitmap *_img_trackln;

#endif /* BITMAPS_H */
