//
// File Autogenerated by SaltyPaw's PNG conversion script
//
//
#ifndef _IMAGES_BIN2C_H_
#define _IMAGES_BIN2C_H_
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
# include <wx/wx.h>
#endif
#include <wx/mstream.h>
//
extern void initialize_bitmaps(void);
//
extern wxBitmap *_img_exp_sq;
extern wxBitmap *_img_oil_rig;
extern wxBitmap *_img_sector;
extern wxBitmap *_img_sector_uscg;
extern wxBitmap *_img_trackln_both;
extern wxBitmap *_img_trackln1;
extern wxBitmap *_img_trackln1_port;
//
#endif // _IMAGES_BIN2C_H_
