/* Autogenerated by png2wx.pl on Sun Sep 16 09:29:37 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_rescue;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_sar;
extern wxString _svg_sar_toggled;
#endif


#endif /* ICONS_H */
