#define PLUGIN_NAME sar
#define PLUGIN_CATALOG_NAME wxS("mike-rossiter-sar")
#define PLUGIN_VERSION_MAJOR 2
#define PLUGIN_VERSION_MINOR 6
#define PLUGIN_VERSION_PATCH 1
#define PLUGIN_VERSION_TWEAK 0
#define PLUGIN_VERSION_DATE "24/06/2020"
#define PLUGIN_COMMON_NAME "sar"
// API version of OCPN to use
#define OCPN_API_VERSION_MAJOR 1
#define OCPN_API_VERSION_MINOR 16
